// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxSxr1a-RkXq6ghNgft4mG6meK_j4nue4',
    appId: '1:664030469320:android:383d5c2ef874e2b1a519fd',
    messagingSenderId: '664030469320',
    projectId: 'faceattendacerealtime-ef119',
    databaseURL: 'https://faceattendacerealtime-ef119-default-rtdb.firebaseio.com',
    storageBucket: 'faceattendacerealtime-ef119.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSjEPgoUF-EtV3CFSVw17-rFnrFitewHo',
    appId: '1:664030469320:ios:e7a39d853b3746c9a519fd',
    messagingSenderId: '664030469320',
    projectId: 'faceattendacerealtime-ef119',
    databaseURL: 'https://faceattendacerealtime-ef119-default-rtdb.firebaseio.com',
    storageBucket: 'faceattendacerealtime-ef119.appspot.com',
    iosBundleId: 'com.example.pds',
  );
}
